version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: loyalty-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: loyalty_dev
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d loyalty_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: loyalty-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "redis_password"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  redisdata:
